version: "3.9"

services:
  dev:
    build: .
    image: task-transfer
    env_file: .env      
    volumes:
      - .:/src/project
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: /bin/bash -c "sleep infinity"
    container_name: task-transfer-1